version: '2'
services:
  elasticback:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    volumes:
      - ../config/elasticback/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports: 
      - '9200:9200'
      - '9300:9300'
#  kibana:
#    image: docker.elastic.co/kibana/kibana:5.6.2
#    ports:
#      - '5601:5601'
#    volumes:
#      - ../config/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
